// basic
try{
    let num = 10;
    console.log(num / 2); // No error,prints 5
}
catch(error) {
    console.log("an error occured:",error.message);
 }